import Nav from './(components)/Nav'
import './globals.css'
import './(styles)/ItsLoaderSpinSmall.css'
import { Inter } from 'next/font/google'

import {config} from '@fortawesome/fontawesome-svg-core'
import '@fortawesome/fontawesome-svg-core/styles.css'

config.autoAddCss = false
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Ticketing App',
  description: 'Generated by Ian Thai Smith',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`bg-page ${inter.className}`}>
        <div className='flex mt-12 flex-col items-center'>
          <Nav/>
          <div className='flex-grow text-default-text'>
            {children}
          </div>
        </div>
      </body>
    </html>
  )
}
